import axios from 'axios';

export const API_KEY = 'e41b6bf1618d053c31d524d479c14b5t';
export const BASE_API_URL = 'https://api.adoptapet.com/search/';

/*export const AXIOS = axios.create({
  baseURL: BASE_API_URL,
});*/

export const ALL_PETS = [
  {
    sex: 'm',
    secondary_breed: null,
    large_results_photo_width: 200,
    results_photo_height: 90,
    primary_breed: 'Domestic Shorthair',
    large_results_photo_url:
      'https://pet-uploads.adoptapet.com/f/e/7/519636661.jpg',
    age: 'adult',
    results_photo_width: 73,
    addr_city: 'Richmond',
    pet_name: 'Sheldon',
    size: null,
    addr_state_code: 'IN',
    results_photo_url: 'https://pet-uploads.adoptapet.com/2/0/4/519636659.jpg',
    large_results_photo_height: 200,
    order: 1,
    details_url:
      'https://api.adoptapet.com/search/pet_details?pet_id=23006284&key=e41b6bf1618d053c31d524d479c14b5t&v=1&output=json',
    pet_id: '23006284',
  },
  {
    addr_state_code: 'IN',
    large_results_photo_url:
      'https://pet-uploads.adoptapet.com/d/d/e/519636754.jpg',
    results_photo_height: 90,
    secondary_breed: 'Pit Bull Terrier',
    order: 1,
    age: 'adult',
    pet_name: 'Kia',
    primary_breed: 'Shar Pei',
    sex: 'f',
    results_photo_width: 61,
    details_url:
      'https://api.adoptapet.com/search/pet_details?pet_id=29985922&key=e41b6bf1618d053c31d524d479c14b5t&v=1&output=json',
    pet_id: '29985922',
    results_photo_url: 'https://pet-uploads.adoptapet.com/3/9/c/519636752.jpg',
    addr_city: 'Richmond',
    large_results_photo_width: 200,
    size: 'Med. 26-60 lbs (12-27 kg)',
    large_results_photo_height: 200,
  },
  {
    addr_state_code: 'IN',
    pet_name: 'Ares',
    size: null,
    large_results_photo_height: 200,
    results_photo_url: 'https://images.adoptapet.com/images/no-cat.gif',
    pet_id: '29665688',
    details_url:
      'https://api.adoptapet.com/search/pet_details?pet_id=29665688&key=e41b6bf1618d053c31d524d479c14b5t&v=1&output=json',
    order: 2,
    large_results_photo_width: 200,
    results_photo_height: '67',
    secondary_breed: 'Domestic Shorthair',
    sex: 'm',
    large_results_photo_url:
      'https://images.adoptapet.com/images/no-cat-large.gif',
    primary_breed: 'Domestic Shorthair',
    addr_city: 'Richmond',
    age: 'adult',
    results_photo_width: '90',
  },
  {
    pet_id: '30070049',
    results_photo_width: 67,
    details_url:
      'https://api.adoptapet.com/search/pet_details?pet_id=30070049&key=e41b6bf1618d053c31d524d479c14b5t&v=1&output=json',
    large_results_photo_width: 200,
    large_results_photo_height: 200,
    size: 'Large 61-100 lbs (28-45 kg)',
    results_photo_url: 'https://pet-uploads.adoptapet.com/9/3/7/518575911.jpg',
    addr_city: 'Richmond',
    age: 'young',
    order: 2,
    addr_state_code: 'IN',
    secondary_breed: null,
    large_results_photo_url:
      'https://pet-uploads.adoptapet.com/b/a/c/518575913.jpg',
    results_photo_height: 90,
    primary_breed: 'Mixed Breed (Medium)',
    sex: 'm',
    pet_name: 'Adam',
  },
  {
    pet_id: '29665012',
    details_url:
      'https://api.adoptapet.com/search/pet_details?pet_id=29665012&key=e41b6bf1618d053c31d524d479c14b5t&v=1&output=json',
    order: 3,
    size: null,
    pet_name: 'Thor',
    addr_state_code: 'IN',
    results_photo_url: 'https://images.adoptapet.com/images/no-cat.gif',
    large_results_photo_height: 200,
    age: 'kitten',
    results_photo_width: '90',
    addr_city: 'Richmond',
    sex: 'm',
    large_results_photo_width: 200,
    secondary_breed: 'Domestic Shorthair',
    results_photo_height: '67',
    primary_breed: 'Domestic Shorthair',
    large_results_photo_url:
      'https://images.adoptapet.com/images/no-cat-large.gif',
  },
  {
    pet_name: 'Hunter',
    sex: 'm',
    primary_breed: 'Mixed Breed (Medium)',
    large_results_photo_url:
      'https://pet-uploads.adoptapet.com/b/f/a/518092028.jpg',
    secondary_breed: null,
    results_photo_height: 90,
    addr_state_code: 'IN',
    age: 'puppy',
    order: 3,
    addr_city: 'Richmond',
    results_photo_url: 'https://pet-uploads.adoptapet.com/9/2/a/518092026.jpg',
    size: 'Small 25 lbs (11 kg) or less',
    large_results_photo_height: 200,
    large_results_photo_width: 200,
    details_url:
      'https://api.adoptapet.com/search/pet_details?pet_id=30050307&key=e41b6bf1618d053c31d524d479c14b5t&v=1&output=json',
    results_photo_width: 68,
    pet_id: '30050307',
  },
  {
    large_results_photo_width: 200,
    results_photo_height: 67,
    secondary_breed: 'Domestic Shorthair',
    sex: 'm',
    large_results_photo_url:
      'https://images.adoptapet.com/images/no-cat-large.gif',
    primary_breed: 'Domestic Shorthair',
    addr_city: 'Richmond',
    results_photo_width: 90,
    age: 'kitten',
    addr_state_code: 'IN',
    size: null,
    pet_name: 'Midas',
    large_results_photo_height: 200,
    results_photo_url: 'https://images.adoptapet.com/images/no-cat.gif',
    pet_id: '29665067',
    details_url:
      'https://api.adoptapet.com/search/pet_details?pet_id=29665067&key=e41b6bf1618d053c31d524d479c14b5t&v=1&output=json',
    order: 4,
  },
  {
    addr_state_code: 'IN',
    results_photo_height: 68,
    large_results_photo_url:
      'https://pet-uploads.adoptapet.com/3/e/e/518137801.jpg',
    secondary_breed: null,
    age: 'puppy',
    order: 4,
    pet_name: 'Charlie',
    sex: 'm',
    primary_breed: 'Mixed Breed (Medium)',
    results_photo_width: 90,
    details_url:
      'https://api.adoptapet.com/search/pet_details?pet_id=30051465&key=e41b6bf1618d053c31d524d479c14b5t&v=1&output=json',
    pet_id: '30051465',
    addr_city: 'Richmond',
    results_photo_url: 'https://pet-uploads.adoptapet.com/5/4/4/518137799.jpg',
    large_results_photo_width: 200,
    size: 'Med. 26-60 lbs (12-27 kg)',
    large_results_photo_height: 200,
  },
  {
    sex: 'f',
    large_results_photo_width: 200,
    secondary_breed: 'Domestic Shorthair',
    results_photo_height: '67',
    primary_breed: 'Domestic Shorthair',
    large_results_photo_url:
      'https://images.adoptapet.com/images/no-cat-large.gif',
    addr_city: 'Richmond',
    results_photo_width: '90',
    age: 'adult',
    pet_name: 'Margo',
    size: null,
    addr_state_code: 'IN',
    results_photo_url: 'https://images.adoptapet.com/images/no-cat.gif',
    large_results_photo_height: 200,
    details_url:
      'https://api.adoptapet.com/search/pet_details?pet_id=29665687&key=e41b6bf1618d053c31d524d479c14b5t&v=1&output=json',
    pet_id: '29665687',
    order: 5,
  },
  {
    details_url:
      'https://api.adoptapet.com/search/pet_details?pet_id=29812747&key=e41b6bf1618d053c31d524d479c14b5t&v=1&output=json',
    results_photo_width: 90,
    pet_id: '29812747',
    addr_city: 'Richmond',
    results_photo_url: 'https://pet-uploads.adoptapet.com/5/3/b/518092122.jpg',
    large_results_photo_height: 200,
    size: 'Large 61-100 lbs (28-45 kg)',
    large_results_photo_width: 200,
    large_results_photo_url:
      'https://pet-uploads.adoptapet.com/1/d/8/518092124.jpg',
    secondary_breed: null,
    results_photo_height: 90,
    addr_state_code: 'IN',
    age: 'adult',
    order: 5,
    pet_name: 'Frida',
    sex: 'f',
    primary_breed: 'Mixed Breed (Medium)',
  },
  {
    pet_id: '29272077',
    details_url:
      'https://api.adoptapet.com/search/pet_details?pet_id=29272077&key=e41b6bf1618d053c31d524d479c14b5t&v=1&output=json',
    order: 6,
    large_results_photo_height: 200,
    results_photo_url: 'https://pet-uploads.adoptapet.com/1/0/5/519635996.jpg',
    addr_state_code: 'IN',
    pet_name: 'Morrison',
    size: null,
    addr_city: 'Richmond',
    results_photo_width: 65,
    age: 'young',
    large_results_photo_url:
      'https://pet-uploads.adoptapet.com/8/1/d/519635998.jpg',
    primary_breed: 'Domestic Mediumhair',
    secondary_breed: null,
    large_results_photo_width: 200,
    results_photo_height: 90,
    sex: 'm',
  },
  {
    results_photo_width: 72,
    addr_city: 'Richmond',
    age: 'young',
    large_results_photo_url:
      'https://pet-uploads.adoptapet.com/7/b/4/519636006.jpg',
    primary_breed: 'Domestic Shorthair',
    secondary_breed: null,
    large_results_photo_width: 200,
    results_photo_height: 90,
    sex: 'f',
    order: 7,
    pet_id: '29075852',
    details_url:
      'https://api.adoptapet.com/search/pet_details?pet_id=29075852&key=e41b6bf1618d053c31d524d479c14b5t&v=1&output=json',
    large_results_photo_height: 200,
    results_photo_url: 'https://pet-uploads.adoptapet.com/6/b/7/519636004.jpg',
    addr_state_code: 'IN',
    pet_name: 'AC #114 Kaleidoscope',
    size: null,
  },
  {
    addr_city: 'Richmond',
    results_photo_url: 'https://pet-uploads.adoptapet.com/8/4/f/518092017.jpg',
    large_results_photo_width: 200,
    size: 'Small 25 lbs (11 kg) or less',
    large_results_photo_height: 200,
    results_photo_width: 90,
    details_url:
      'https://api.adoptapet.com/search/pet_details?pet_id=30050306&key=e41b6bf1618d053c31d524d479c14b5t&v=1&output=json',
    pet_id: '30050306',
    pet_name: 'Daisy',
    sex: 'f',
    primary_breed: 'Mixed Breed (Medium)',
    addr_state_code: 'IN',
    large_results_photo_url:
      'https://pet-uploads.adoptapet.com/b/2/a/518092019.jpg',
    secondary_breed: null,
    results_photo_height: 68,
    age: 'puppy',
    order: 6,
  },
  {
    results_photo_url: 'https://pet-uploads.adoptapet.com/e/f/c/519636012.jpg',
    large_results_photo_height: 200,
    size: null,
    pet_name: 'Lewy',
    addr_state_code: 'IN',
    details_url:
      'https://api.adoptapet.com/search/pet_details?pet_id=29993814&key=e41b6bf1618d053c31d524d479c14b5t&v=1&output=json',
    order: 8,
    pet_id: '29993814',
    primary_breed: 'Domestic Longhair',
    large_results_photo_url:
      'https://pet-uploads.adoptapet.com/f/9/d/519636014.jpg',
    sex: 'm',
    large_results_photo_width: 200,
    results_photo_height: 90,
    secondary_breed: null,
    addr_city: 'Richmond',
    age: 'adult',
    results_photo_width: 81,
  },
  {
    pet_id: '29354626',
    details_url:
      'https://api.adoptapet.com/search/pet_details?pet_id=29354626&key=e41b6bf1618d053c31d524d479c14b5t&v=1&output=json',
    order: 9,
    large_results_photo_height: 200,
    results_photo_url: 'https://pet-uploads.adoptapet.com/8/3/c/519636020.jpg',
    addr_state_code: 'IN',
    size: null,
    pet_name: 'Sienna',
    results_photo_width: 88,
    age: 'adult',
    addr_city: 'Richmond',
    large_results_photo_url:
      'https://pet-uploads.adoptapet.com/7/b/3/519636022.jpg',
    primary_breed: 'Domestic Shorthair',
    large_results_photo_width: 200,
    secondary_breed: null,
    results_photo_height: 90,
    sex: 'f',
  },
  {
    pet_name: 'Delphinium',
    size: null,
    addr_state_code: 'IN',
    results_photo_url: 'https://pet-uploads.adoptapet.com/8/7/7/519636028.jpg',
    large_results_photo_height: 200,
    pet_id: '28579844',
    order: 10,
    details_url:
      'https://api.adoptapet.com/search/pet_details?pet_id=28579844&key=e41b6bf1618d053c31d524d479c14b5t&v=1&output=json',
    sex: 'f',
    results_photo_height: 90,
    large_results_photo_width: 200,
    secondary_breed: null,
    primary_breed: 'Domestic Shorthair',
    large_results_photo_url:
      'https://pet-uploads.adoptapet.com/3/5/f/519636030.jpg',
    age: 'adult',
    results_photo_width: 77,
    addr_city: 'Richmond',
  },
  {
    pet_name: 'Rhonda',
    primary_breed: 'Mixed Breed (Medium)',
    sex: 'f',
    addr_state_code: 'IN',
    large_results_photo_url:
      'https://pet-uploads.adoptapet.com/a/a/f/518091977.jpg',
    secondary_breed: null,
    results_photo_height: 90,
    age: null,
    order: 7,
    results_photo_url: 'https://pet-uploads.adoptapet.com/5/3/e/518091975.jpg',
    addr_city: 'Richmond',
    large_results_photo_width: 200,
    size: 'Med. 26-60 lbs (12-27 kg)',
    large_results_photo_height: 200,
    results_photo_width: 68,
    details_url:
      'https://api.adoptapet.com/search/pet_details?pet_id=30050302&key=e41b6bf1618d053c31d524d479c14b5t&v=1&output=json',
    pet_id: '30050302',
  },
  {
    details_url:
      'https://api.adoptapet.com/search/pet_details?pet_id=28866152&key=e41b6bf1618d053c31d524d479c14b5t&v=1&output=json',
    results_photo_width: 90,
    pet_id: '28866152',
    results_photo_url: 'https://pet-uploads.adoptapet.com/f/d/5/518091955.jpg',
    addr_city: 'Richmond',
    size: 'Large 61-100 lbs (28-45 kg)',
    large_results_photo_height: 200,
    large_results_photo_width: 200,
    results_photo_height: 90,
    large_results_photo_url:
      'https://pet-uploads.adoptapet.com/5/4/9/518091957.jpg',
    secondary_breed: null,
    addr_state_code: 'IN',
    age: 'adult',
    order: 8,
    pet_name: 'Joey',
    primary_breed: 'Mixed Breed (Medium)',
    sex: 'm',
  },
  {
    order: 9,
    age: 'adult',
    large_results_photo_url:
      'https://pet-uploads.adoptapet.com/3/9/c/518091943.jpg',
    secondary_breed: null,
    results_photo_height: 90,
    addr_state_code: 'IN',
    primary_breed: 'Mixed Breed (Medium)',
    sex: 'm',
    pet_name: 'Keenai',
    pet_id: '30050301',
    details_url:
      'https://api.adoptapet.com/search/pet_details?pet_id=30050301&key=e41b6bf1618d053c31d524d479c14b5t&v=1&output=json',
    results_photo_width: 90,
    large_results_photo_height: 200,
    size: 'Med. 26-60 lbs (12-27 kg)',
    large_results_photo_width: 200,
    results_photo_url: 'https://pet-uploads.adoptapet.com/5/8/4/518091941.jpg',
    addr_city: 'Richmond',
  },
  {
    order: 10,
    age: 'adult',
    large_results_photo_url:
      'https://pet-uploads.adoptapet.com/8/1/0/513664361.jpg',
    results_photo_height: 90,
    secondary_breed: null,
    addr_state_code: 'IN',
    sex: 'f',
    primary_breed: 'Mixed Breed (Medium)',
    pet_name: 'Patty',
    pet_id: '29856092',
    details_url:
      'https://api.adoptapet.com/search/pet_details?pet_id=29856092&key=e41b6bf1618d053c31d524d479c14b5t&v=1&output=json',
    results_photo_width: 68,
    size: 'Large 61-100 lbs (28-45 kg)',
    large_results_photo_height: 200,
    large_results_photo_width: 200,
    addr_city: 'Richmond',
    results_photo_url: 'https://pet-uploads.adoptapet.com/5/b/a/513664359.jpg',
  },
  {
    results_photo_url: 'https://pet-uploads.adoptapet.com/3/0/a/510927928.jpg',
    addr_city: 'Richmond',
    large_results_photo_height: 200,
    size: 'Small 25 lbs (11 kg) or less',
    large_results_photo_width: 200,
    details_url:
      'https://api.adoptapet.com/search/pet_details?pet_id=29735316&key=e41b6bf1618d053c31d524d479c14b5t&v=1&output=json',
    results_photo_width: 68,
    pet_id: '29735316',
    pet_name: 'Dean',
    primary_breed: 'Mixed Breed (Medium)',
    sex: 'm',
    large_results_photo_url:
      'https://pet-uploads.adoptapet.com/6/f/9/510927930.jpg',
    results_photo_height: 90,
    secondary_breed: null,
    addr_state_code: 'IN',
    age: null,
    order: 11,
  },
];
